Solution
mate-academy/py-taxi-service-home-page pull request #466
Opened 2023-11-13 16:46 UTC by vshvanska

![home_page](https://github.com/mate-academy/py-taxi-service-home-page/assets/141127161/b170d5ea-0cd6-4869-ba6f-aa7207219532)

2023-11-13 17:26 UTC, mykolamateichuk commented on taxi/urls.py
> +urlpatterns = [path("", index, name="index")]
It's better to have urlpatterns open like this:
`
urlpatterns = [
    ...
]
`
then you can add elements to it more quickly and it becomes more readable.

2023-11-13 17:27 UTC, mykolamateichuk approved these changes

2023-11-15 14:08 UTC, fsocie7y requested changes

2023-11-15 14:08 UTC, fsocie7y commented on templates/taxi/index.html
> +{% endblock %}
add blank line to end of file)

2025-01-27 19:00 UTC, closed without merging