Solution
mate-academy/py-taxi-service-home-page pull request #55
Opened 2022-07-15 08:10 UTC by SairusQw

2022-07-15 08:19 UTC, Abnormaltype requested changes
attach screenshots and delete DB from PR, also don't change the `README` file

2022-07-16 08:05 UTC, SairusQw commented
<img width="1440" alt="Снимок экрана 2022-07-16 в 11 02 08" src="https://user-images.githubusercontent.com/99564018/179346313-e95b421b-f5fa-4bfb-83e3-d4e7b31e6da2.png">

2022-07-18 12:38 UTC, IvanRamyk requested changes

2022-07-18 12:38 UTC, IvanRamyk requested changes

2022-07-18 12:38 UTC, IvanRamyk commented on static/css/styles.css
> +}
Please, add an empty line at the end of the file

2022-09-27 07:28 UTC, closed without merging